name: tenementz
description: Flutter multiplatform app for Tenementz.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: any
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  firebase_auth: null
  firebase_messaging: ^14.6.1
  firebase_core: ^2.4.1
  firebase_ui_firestore: ^1.5.6
  flutter_animate: ^4.1.1+1
  google_sign_in: ^5.0.7
  http: ^0.13.6
  image_picker: ^0.8.9
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  lottie: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.14
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.0
  sizer: ^2.0.15
  url_launcher: ^6.1.10
  velocity_x: any
  flutter_cache_manager: ^3.3.1
  flutter_timezone: ^1.0.7
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  flutter_carousel_slider: ^1.1.0
 
module:
  androidX: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.2.3
  riverpod_lint: 1.3.2

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  
  fonts:
    - family: Pop
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Popb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

