// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78Rp7W0bdoIsCOLl47KjbPFiS-M1hJ6M',
    appId: '1:874903449042:android:ea62820d0624d648592c0b',
    messagingSenderId: '874903449042',
    projectId: 'house-master-47f45',
    databaseURL: 'https://house-master-47f45.firebaseio.com',
    storageBucket: 'house-master-47f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs-RL-bF3aVtplqBKZiO6uTy2lRTv38j4',
    appId: '1:874903449042:ios:4e177c779d1cc9f8592c0b',
    messagingSenderId: '874903449042',
    projectId: 'house-master-47f45',
    databaseURL: 'https://house-master-47f45.firebaseio.com',
    storageBucket: 'house-master-47f45.appspot.com',
    iosClientId: '874903449042-rpnp2cnn7g41tebasor804e19akgqc8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenementz',
  );
}
